name: Build MoneyTracker (Cross-Platform, CMake)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # ---------------- WINDOWS ----------------
    - name: Set up MSVC (Windows only)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    # ---------------- LINUX ----------------
    - name: Install dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xorg-dev \
          libglu1-mesa-dev \
          pkg-config

    # ---------------- CONFIGURE + BUILD ----------------
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

    # ---------------- TESTS ----------------
    - name: Run tests (if any)
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} || echo "No tests defined"

    # ---------------- ARTIFACTS ----------------
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MoneyTracker-${{env.BUILD_TYPE}}-${{ matrix.os }}
        path: |
          build/**/*.exe
          build/**/*.dll
          build/**/*.so
          build/**/*.dylib
          build/resources/**
